// window.MOCK_SPOTS must be an array of spot objects
window.MOCK_SPOTS = [
    {
        "spot_datetime": "2026-02-18 16:16:06",
        "spot_time": "1616Z",
        "band": "15",
        "frequency": "21075.4",
        "spotted": "MI0CBH",
        "spotted_dxcc": "265",
        "spotted_flag": "GB-NIR",
        "spotted_country": "NORTHERN IRELAND",
        "spotted_continent": "EU",
        "spotter": "KX2S",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "rtty",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:16:01",
        "spot_time": "1615Z",
        "band": "10",
        "frequency": "28180.0",
        "spotted": "AA5WH",
        "spotted_dxcc": "291",
        "spotted_flag": "US",
        "spotted_country": "UNITED STATES OF AMERICA",
        "spotted_continent": "NA",
        "spotter": "KD2WDR",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "ft8",
        "spotter_comment": "FT4 -2dB 770 Hz CQ            "
    },
    {
        "spot_datetime": "2026-02-18 16:15:56",
        "spot_time": "1615Z",
        "band": "10",
        "frequency": "28422.0",
        "spotted": "N8II",
        "spotted_dxcc": "291",
        "spotted_flag": "US",
        "spotted_country": "UNITED STATES OF AMERICA",
        "spotted_continent": "NA",
        "spotter": "PD7V",
        "spotter_dxcc": "263",
        "spotter_flag": "NL",
        "spotter_country": "NETHERLANDS",
        "spotter_continent": "EU",
        "mode": "rtty",
        "spotter_comment": "Thnx visit my qrz page please "
    },
    {
        "spot_datetime": "2026-02-18 16:15:17",
        "spot_time": "1615Z",
        "band": "10",
        "frequency": "28074.0",
        "spotted": "OX3LX",
        "spotted_dxcc": "237",
        "spotted_flag": "GL",
        "spotted_country": "GREENLAND",
        "spotted_continent": "NA",
        "spotter": "EB5AN",
        "spotter_dxcc": "281",
        "spotter_flag": "ES",
        "spotter_country": "SPAIN",
        "spotter_continent": "EU",
        "mode": "cw",
        "spotter_comment": "FT8 -11 dB 2926 Hz            "
    },
    {
        "spot_datetime": "2026-02-18 16:15:04",
        "spot_time": "1614Z",
        "band": "002",
        "frequency": "5760900.0",
        "spotted": "GB3OHM\/B",
        "spotted_dxcc": "223",
        "spotted_flag": "GB-ENG",
        "spotted_country": "ENGLAND",
        "spotted_continent": "EU",
        "spotter": "G0API",
        "spotter_dxcc": "223",
        "spotter_flag": "GB-ENG",
        "spotter_country": "ENGLAND",
        "spotter_continent": "EU",
        "mode": "lsb",
        "spotter_comment": "IO80XS(RS)IO92AJ 52S          "
    },
    {
        "spot_datetime": "2026-02-18 16:14:59",
        "spot_time": "1614Z",
        "band": "15",
        "frequency": "21033.0",
        "spotted": "W1WA\/5",
        "spotted_dxcc": "291",
        "spotted_flag": "US",
        "spotted_country": "UNITED STATES OF AMERICA",
        "spotted_continent": "NA",
        "spotter": "PA3GUU",
        "spotter_dxcc": "263",
        "spotter_flag": "NL",
        "spotter_country": "NETHERLANDS",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": "Booming signalin JO21         "
    },
    {
        "spot_datetime": "2026-02-18 16:14:52",
        "spot_time": "1614Z",
        "band": "30",
        "frequency": "10115.0",
        "spotted": "DP5ANT",
        "spotted_dxcc": "230",
        "spotted_flag": "DE",
        "spotted_country": "FEDERAL REPUBLIC OF GERMANY",
        "spotted_continent": "EU",
        "spotter": "DK5HH",
        "spotter_dxcc": "230",
        "spotter_flag": "DE",
        "spotter_country": "FEDERAL REPUBLIC OF GERMANY",
        "spotter_continent": "EU",
        "mode": "cw",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:14:47",
        "spot_time": "1614Z",
        "band": "40",
        "frequency": "7108.0",
        "spotted": "EA7HTE",
        "spotted_dxcc": "281",
        "spotted_flag": "ES",
        "spotted_country": "SPAIN",
        "spotted_continent": "EU",
        "spotter": "EA7HPI",
        "spotter_dxcc": "281",
        "spotter_flag": "ES",
        "spotter_country": "SPAIN",
        "spotter_continent": "EU",
        "mode": "lsb",
        "spotter_comment": "HERMANDADES                   "
    },
    {
        "spot_datetime": "2026-02-18 16:14:43",
        "spot_time": "1614Z",
        "band": "40",
        "frequency": "7180.0",
        "spotted": "IW5DAX",
        "spotted_dxcc": "248",
        "spotted_flag": "IT",
        "spotted_country": "ITALY",
        "spotted_continent": "EU",
        "spotter": "IU5ANK",
        "spotter_dxcc": "248",
        "spotter_flag": "IT",
        "spotter_country": "ITALY",
        "spotter_continent": "EU",
        "mode": "cw",
        "spotter_comment": "star trek 2026 e iono         "
    },
    {
        "spot_datetime": "2026-02-18 16:14:11",
        "spot_time": "1614Z",
        "band": "20",
        "frequency": "14080.0",
        "spotted": "IQ2DB",
        "spotted_dxcc": "248",
        "spotted_flag": "IT",
        "spotted_country": "ITALY",
        "spotted_continent": "EU",
        "spotter": "IW2IBU",
        "spotter_dxcc": "248",
        "spotter_flag": "IT",
        "spotter_country": "ITALY",
        "spotter_continent": "EU",
        "mode": "rtty",
        "spotter_comment": "Volta Award 2026 FT4          "
    },
    {
        "spot_datetime": "2026-02-18 16:14:07",
        "spot_time": "1614Z",
        "band": "10",
        "frequency": "28008.0",
        "spotted": "ZV8PI",
        "spotted_dxcc": "108",
        "spotted_flag": "BR",
        "spotted_country": "BRAZIL",
        "spotted_continent": "SA",
        "spotter": "PY1FR",
        "spotter_dxcc": "108",
        "spotter_flag": "BR",
        "spotter_country": "BRAZIL",
        "spotter_continent": "SA",
        "mode": "cw",
        "spotter_comment": "Labre Awards 92 Years         "
    },
    {
        "spot_datetime": "2026-02-18 16:14:02",
        "spot_time": "1614Z",
        "band": "40",
        "frequency": "7088.0",
        "spotted": "EA2DT\/P",
        "spotted_dxcc": "281",
        "spotted_flag": "ES",
        "spotted_country": "SPAIN",
        "spotted_continent": "EU",
        "spotter": "EA1OX",
        "spotter_dxcc": "281",
        "spotter_flag": "ES",
        "spotter_country": "SPAIN",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:13:58",
        "spot_time": "1613Z",
        "band": "10",
        "frequency": "28019.9",
        "spotted": "ON6MG",
        "spotted_dxcc": "209",
        "spotted_flag": "BE",
        "spotted_country": "BELGIUM",
        "spotted_continent": "EU",
        "spotter": "ZV2LB",
        "spotter_dxcc": "108",
        "spotter_flag": "BR",
        "spotter_country": "BRAZIL",
        "spotter_continent": "SA",
        "mode": "ft8",
        "spotter_comment": "CW                            "
    },
    {
        "spot_datetime": "2026-02-18 16:13:54",
        "spot_time": "1613Z",
        "band": "2",
        "frequency": "144174.0",
        "spotted": "DJ6VX",
        "spotted_dxcc": "230",
        "spotted_flag": "DE",
        "spotted_country": "FEDERAL REPUBLIC OF GERMANY",
        "spotted_continent": "EU",
        "spotter": "G4TRA",
        "spotter_dxcc": "223",
        "spotter_flag": "GB-ENG",
        "spotter_country": "ENGLAND",
        "spotter_continent": "EU",
        "mode": "rtty",
        "spotter_comment": "TAG BUNDESWEHR                "
    },
    {
        "spot_datetime": "2026-02-18 16:13:49",
        "spot_time": "1613Z",
        "band": "002",
        "frequency": "5760909.0",
        "spotted": "GB3ZME\/B",
        "spotted_dxcc": "223",
        "spotted_flag": "GB-ENG",
        "spotted_country": "ENGLAND",
        "spotted_continent": "EU",
        "spotter": "G0API",
        "spotter_dxcc": "223",
        "spotter_flag": "GB-ENG",
        "spotter_country": "ENGLAND",
        "spotter_continent": "EU",
        "mode": "lsb",
        "spotter_comment": "IO80XS(RS)IO82RP 54S          "
    },
    {
        "spot_datetime": "2026-02-18 16:13:31",
        "spot_time": "1613Z",
        "band": "15",
        "frequency": "21075.4",
        "spotted": "E72T",
        "spotted_dxcc": "501",
        "spotted_flag": "BA",
        "spotted_country": "BOSNIA-HERZEGOVINA",
        "spotted_continent": "EU",
        "spotter": "KX2S",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "rtty",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:13:12",
        "spot_time": "1613Z",
        "band": "10",
        "frequency": "28435.0",
        "spotted": "J52EC",
        "spotted_dxcc": "109",
        "spotted_flag": "GW",
        "spotted_country": "GUINEA-BISSAU",
        "spotted_continent": "AF",
        "spotter": "ON7MP",
        "spotter_dxcc": "209",
        "spotter_flag": "BE",
        "spotter_country": "BELGIUM",
        "spotter_continent": "EU",
        "mode": "usb",
        "spotter_comment": "Tks Livio-57 in JO20mo-GL and "
    },
    {
        "spot_datetime": "2026-02-18 16:13:03",
        "spot_time": "1612Z",
        "band": "15",
        "frequency": "21300.0",
        "spotted": "N1WMN",
        "spotted_dxcc": "291",
        "spotted_flag": "US",
        "spotted_country": "UNITED STATES OF AMERICA",
        "spotted_continent": "NA",
        "spotter": "HA5CPN",
        "spotter_dxcc": "239",
        "spotter_flag": "HU",
        "spotter_country": "HUNGARY",
        "spotter_continent": "EU",
        "mode": "cw",
        "spotter_comment": "All the best_5.5_TNX_QSO      "
    },
    {
        "spot_datetime": "2026-02-18 16:12:58",
        "spot_time": "1612Z",
        "band": "15",
        "frequency": "21033.0",
        "spotted": "W1AW\/5",
        "spotted_dxcc": "291",
        "spotted_flag": "US",
        "spotted_country": "UNITED STATES OF AMERICA",
        "spotted_continent": "NA",
        "spotter": "PA3GUU",
        "spotter_dxcc": "263",
        "spotter_flag": "NL",
        "spotter_country": "NETHERLANDS",
        "spotter_continent": "EU",
        "mode": "lsb",
        "spotter_comment": "Booming signal in JO21        "
    },
    {
        "spot_datetime": "2026-02-18 16:12:53",
        "spot_time": "1612Z",
        "band": "10",
        "frequency": "28007.1",
        "spotted": "E74OW",
        "spotted_dxcc": "501",
        "spotted_flag": "BA",
        "spotted_country": "BOSNIA-HERZEGOVINA",
        "spotted_continent": "EU",
        "spotter": "W3LPL",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "rtty",
        "spotter_comment": "Heard in PA                   "
    },
    {
        "spot_datetime": "2026-02-18 16:12:49",
        "spot_time": "1612Z",
        "band": "10",
        "frequency": "28386.0",
        "spotted": "VA3TAL",
        "spotted_dxcc": "1",
        "spotted_flag": "CA",
        "spotted_country": "CANADA",
        "spotted_continent": "NA",
        "spotter": "EA3CL",
        "spotter_dxcc": "281",
        "spotter_flag": "ES",
        "spotter_country": "SPAIN",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": "JN11BJ<>FN04CN                "
    },
    {
        "spot_datetime": "2026-02-18 16:12:36",
        "spot_time": "1612Z",
        "band": "15",
        "frequency": "21075.4",
        "spotted": "IU5RTR",
        "spotted_dxcc": "248",
        "spotted_flag": "IT",
        "spotted_country": "ITALY",
        "spotted_continent": "EU",
        "spotter": "KX2S",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "ft8",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:12:32",
        "spot_time": "1612Z",
        "band": "001",
        "frequency": "10368940.0",
        "spotted": "GB3GCT\/B",
        "spotted_dxcc": "223",
        "spotted_flag": "GB-ENG",
        "spotted_country": "ENGLAND",
        "spotted_continent": "EU",
        "spotter": "G0API",
        "spotter_dxcc": "223",
        "spotter_flag": "GB-ENG",
        "spotter_country": "ENGLAND",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": "IO80XS(RS)IO91IJ 56S          "
    },
    {
        "spot_datetime": "2026-02-18 16:12:27",
        "spot_time": "1611Z",
        "band": "10",
        "frequency": "28180.0",
        "spotted": "ZV8PA",
        "spotted_dxcc": "108",
        "spotted_flag": "BR",
        "spotted_country": "BRAZIL",
        "spotted_continent": "SA",
        "spotter": "PU2LJH",
        "spotter_dxcc": "108",
        "spotter_flag": "BR",
        "spotter_country": "BRAZIL",
        "spotter_continent": "SA",
        "mode": "lsb",
        "spotter_comment": "tnx qso 73 labre 92 anos      "
    },
    {
        "spot_datetime": "2026-02-18 16:12:18",
        "spot_time": "1612Z",
        "band": "40",
        "frequency": "7088.0",
        "spotted": "EA2DT\/P",
        "spotted_dxcc": "281",
        "spotted_flag": "ES",
        "spotted_country": "SPAIN",
        "spotted_continent": "EU",
        "spotter": "EA4GJP",
        "spotter_dxcc": "281",
        "spotter_flag": "ES",
        "spotter_country": "SPAIN",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": "59  POTA ES-1843              "
    },
    {
        "spot_datetime": "2026-02-18 16:12:10",
        "spot_time": "1612Z",
        "band": "40",
        "frequency": "7127.0",
        "spotted": "IZ0PAP",
        "spotted_dxcc": "248",
        "spotted_flag": "IT",
        "spotted_country": "ITALY",
        "spotted_continent": "EU",
        "spotter": "9A5ACK",
        "spotter_dxcc": "497",
        "spotter_flag": "HR",
        "spotter_country": "CROATIA",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": "TNX for QSO, 73 Ivan          "
    },
    {
        "spot_datetime": "2026-02-18 16:11:50",
        "spot_time": "1611Z",
        "band": "10",
        "frequency": "28434.8",
        "spotted": "J52EC",
        "spotted_dxcc": "109",
        "spotted_flag": "GW",
        "spotted_country": "GUINEA-BISSAU",
        "spotted_continent": "AF",
        "spotter": "IZ1WYO",
        "spotter_dxcc": "248",
        "spotter_flag": "IT",
        "spotter_country": "ITALY",
        "spotter_continent": "EU",
        "mode": "lsb",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:11:40",
        "spot_time": "1611Z",
        "band": "20",
        "frequency": "14020.3",
        "spotted": "V3T",
        "spotted_dxcc": "66",
        "spotted_flag": "BZ",
        "spotted_country": "BELIZE",
        "spotted_continent": "NA",
        "spotter": "WC0W",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "lsb",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:11:35",
        "spot_time": "1611Z",
        "band": "001",
        "frequency": "10368910.0",
        "spotted": "GB3SCX\/B",
        "spotted_dxcc": "223",
        "spotted_flag": "GB-ENG",
        "spotted_country": "ENGLAND",
        "spotted_continent": "EU",
        "spotter": "G0API",
        "spotter_dxcc": "223",
        "spotter_flag": "GB-ENG",
        "spotter_country": "ENGLAND",
        "spotter_continent": "EU",
        "mode": "usb",
        "spotter_comment": "IO80XS IO80UU 599          "
    },
    {
        "spot_datetime": "2026-02-18 16:11:31",
        "spot_time": "1611Z",
        "band": "20",
        "frequency": "14272.4",
        "spotted": "W1AW\/5",
        "spotted_dxcc": "291",
        "spotted_flag": "US",
        "spotted_country": "UNITED STATES OF AMERICA",
        "spotted_continent": "NA",
        "spotter": "N8WRL",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "ft8",
        "spotter_comment": "L*O*U*D!!!                    "
    },
    {
        "spot_datetime": "2026-02-18 16:11:26",
        "spot_time": "1611Z",
        "band": "40",
        "frequency": "7021.5",
        "spotted": "HG80EART",
        "spotted_dxcc": "239",
        "spotted_flag": "HU",
        "spotted_country": "HUNGARY",
        "spotted_continent": "EU",
        "spotter": "RA3QOP",
        "spotter_dxcc": "54",
        "spotter_flag": "RU",
        "spotter_country": "EUROPEAN RUSSIA",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": "EME AWARD KESENEM             "
    },
    {
        "spot_datetime": "2026-02-18 16:11:07",
        "spot_time": "1611Z",
        "band": "40",
        "frequency": "7074.0",
        "spotted": "II2V",
        "spotted_dxcc": "248",
        "spotted_flag": "IT",
        "spotted_country": "ITALY",
        "spotted_continent": "EU",
        "spotter": "IK2LOL",
        "spotter_dxcc": "248",
        "spotter_flag": "IT",
        "spotter_country": "ITALY",
        "spotter_continent": "EU",
        "mode": "lsb",
        "spotter_comment": "FT4 Volta Award 2026          "
    },
    {
        "spot_datetime": "2026-02-18 16:11:02",
        "spot_time": "1611Z",
        "band": "15",
        "frequency": "21075.4",
        "spotted": "IK1RQX",
        "spotted_dxcc": "248",
        "spotted_flag": "IT",
        "spotted_country": "ITALY",
        "spotted_continent": "EU",
        "spotter": "KX2S",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "ft8",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:10:57",
        "spot_time": "1610Z",
        "band": "002",
        "frequency": "5760921.0",
        "spotted": "GB3FNM\/B",
        "spotted_dxcc": "223",
        "spotted_flag": "GB-ENG",
        "spotted_country": "ENGLAND",
        "spotted_continent": "EU",
        "spotter": "G0API",
        "spotter_dxcc": "223",
        "spotter_flag": "GB-ENG",
        "spotter_country": "ENGLAND",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": "IO80XS(RS)IO91OF 54S          "
    },
    {
        "spot_datetime": "2026-02-18 16:10:44",
        "spot_time": "1610Z",
        "band": "40",
        "frequency": "7009.0",
        "spotted": "II3MNA",
        "spotted_dxcc": "248",
        "spotted_flag": "IT",
        "spotted_country": "ITALY",
        "spotted_continent": "EU",
        "spotter": "IW1DQS",
        "spotter_dxcc": "248",
        "spotter_flag": "IT",
        "spotter_country": "ITALY",
        "spotter_continent": "EU",
        "mode": "lsb",
        "spotter_comment": "CW 599 from JN65              "
    },
    {
        "spot_datetime": "2026-02-18 16:10:32",
        "spot_time": "1610Z",
        "band": "20",
        "frequency": "14009.1",
        "spotted": "EU2M",
        "spotted_dxcc": "27",
        "spotted_flag": "BY",
        "spotted_country": "BELARUS",
        "spotted_continent": "EU",
        "spotter": "LZ1VL",
        "spotter_dxcc": "212",
        "spotter_flag": "BG",
        "spotter_country": "BULGARIA",
        "spotter_continent": "EU",
        "mode": "rtty",
        "spotter_comment": "CW                            "
    },
    {
        "spot_datetime": "2026-02-18 16:10:21",
        "spot_time": "1610Z",
        "band": "10",
        "frequency": "28074.0",
        "spotted": "K0TC",
        "spotted_dxcc": "291",
        "spotted_flag": "US",
        "spotted_country": "UNITED STATES OF AMERICA",
        "spotted_continent": "NA",
        "spotter": "IT9IRP",
        "spotter_dxcc": "248",
        "spotter_flag": "IT",
        "spotter_country": "ITALY",
        "spotter_continent": "EU",
        "mode": "lsb",
        "spotter_comment": "Tnx 73 -                      "
    },
    {
        "spot_datetime": "2026-02-18 16:10:14",
        "spot_time": "1610Z",
        "band": "12",
        "frequency": "24917.0",
        "spotted": "P40MC",
        "spotted_dxcc": "91",
        "spotted_flag": "AW",
        "spotted_country": "ARUBA",
        "spotted_continent": "SA",
        "spotter": "EA5D",
        "spotter_dxcc": "281",
        "spotter_flag": "ES",
        "spotter_country": "SPAIN",
        "spotter_continent": "EU",
        "mode": "lsb",
        "spotter_comment": "FT8 -09 JN00BB<>FK42XN        "
    },
    {
        "spot_datetime": "2026-02-18 16:10:09",
        "spot_time": "1610Z",
        "band": "15",
        "frequency": "21075.4",
        "spotted": "UR4QFP",
        "spotted_dxcc": "288",
        "spotted_flag": "UA",
        "spotted_country": "UKRAINE",
        "spotted_continent": "EU",
        "spotter": "KX2S",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "usb",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:10:05",
        "spot_time": "1609Z",
        "band": "20",
        "frequency": "14272.4",
        "spotted": "W1AW\/5",
        "spotted_dxcc": "291",
        "spotted_flag": "US",
        "spotted_country": "UNITED STATES OF AMERICA",
        "spotted_continent": "NA",
        "spotter": "WA7TT",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "ft8",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:10:00",
        "spot_time": "1609Z",
        "band": "002",
        "frequency": "5760905.0",
        "spotted": "GB3SCC\/B",
        "spotted_dxcc": "223",
        "spotted_flag": "GB-ENG",
        "spotted_country": "ENGLAND",
        "spotted_continent": "EU",
        "spotter": "G0API",
        "spotter_dxcc": "223",
        "spotter_flag": "GB-ENG",
        "spotter_country": "ENGLAND",
        "spotter_continent": "EU",
        "mode": "lsb",
        "spotter_comment": "IO80XS IO80UU 599          "
    },
    {
        "spot_datetime": "2026-02-18 16:09:55",
        "spot_time": "1608Z",
        "band": "10",
        "frequency": "28180.0",
        "spotted": "SV2AOB",
        "spotted_dxcc": "236",
        "spotted_flag": "GR",
        "spotted_country": "GREECE",
        "spotted_continent": "EU",
        "spotter": "PU2LJH",
        "spotter_dxcc": "108",
        "spotter_flag": "BR",
        "spotter_country": "BRAZIL",
        "spotter_continent": "SA",
        "mode": "ft8",
        "spotter_comment": "FT4 +12 dB 2182 Hz            "
    },
    {
        "spot_datetime": "2026-02-18 16:09:51",
        "spot_time": "1609Z",
        "band": "12",
        "frequency": "24919.0",
        "spotted": "KA2MGE",
        "spotted_dxcc": "291",
        "spotted_flag": "US",
        "spotted_country": "UNITED STATES OF AMERICA",
        "spotted_continent": "NA",
        "spotter": "IU0CSH",
        "spotter_dxcc": "248",
        "spotter_flag": "IT",
        "spotter_country": "ITALY",
        "spotter_continent": "EU",
        "mode": "rtty",
        "spotter_comment": "ft4 73                        "
    },
    {
        "spot_datetime": "2026-02-18 16:09:46",
        "spot_time": "1609Z",
        "band": "10",
        "frequency": "28353.0",
        "spotted": "VP8TM\/P",
        "spotted_dxcc": "141",
        "spotted_flag": "FK",
        "spotted_country": "FALKLAND ISLANDS",
        "spotted_continent": "SA",
        "spotter": "DK7RD",
        "spotter_dxcc": "230",
        "spotter_flag": "DE",
        "spotter_country": "FEDERAL REPUBLIC OF GERMANY",
        "spotter_continent": "EU",
        "mode": "lsb",
        "spotter_comment": "lsn up 3, SOTA VP8\/WF-054     "
    },
    {
        "spot_datetime": "2026-02-18 16:09:42",
        "spot_time": "1609Z",
        "band": "15",
        "frequency": "21203.0",
        "spotted": "VE9CF",
        "spotted_dxcc": "1",
        "spotted_flag": "CA",
        "spotted_country": "CANADA",
        "spotted_continent": "NA",
        "spotter": "OH0M",
        "spotter_dxcc": "5",
        "spotter_flag": "AX",
        "spotter_country": "ALAND ISLANDS",
        "spotter_continent": "EU",
        "mode": "cw",
        "spotter_comment": "WWFF VEFF-3789                "
    },
    {
        "spot_datetime": "2026-02-18 16:09:38",
        "spot_time": "1609Z",
        "band": "20",
        "frequency": "14271.0",
        "spotted": "IW3HUD",
        "spotted_dxcc": "248",
        "spotted_flag": "IT",
        "spotted_country": "ITALY",
        "spotted_continent": "EU",
        "spotter": "SV1FZZ",
        "spotter_dxcc": "236",
        "spotter_flag": "GR",
        "spotter_country": "GREECE",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": "tnx Enrico 5\/9                "
    },
    {
        "spot_datetime": "2026-02-18 16:09:33",
        "spot_time": "1609Z",
        "band": "30",
        "frequency": "10136.0",
        "spotted": "KE7QAR",
        "spotted_dxcc": "291",
        "spotted_flag": "US",
        "spotted_country": "UNITED STATES OF AMERICA",
        "spotted_continent": "NA",
        "spotter": "N5SUJ",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "usb",
        "spotter_comment": "DM95<>DN26WE                  "
    },
    {
        "spot_datetime": "2026-02-18 16:09:13",
        "spot_time": "1609Z",
        "band": "OOB",
        "frequency": "3400905.0",
        "spotted": "GB3SCF\/B",
        "spotted_dxcc": "223",
        "spotted_flag": "GB-ENG",
        "spotted_country": "ENGLAND",
        "spotted_continent": "EU",
        "spotter": "G0API",
        "spotter_dxcc": "223",
        "spotter_flag": "GB-ENG",
        "spotter_country": "ENGLAND",
        "spotter_continent": "EU",
        "mode": "cw",
        "spotter_comment": "IO80XS IO80UU 599          "
    },
    {
        "spot_datetime": "2026-02-18 16:09:01",
        "spot_time": "1608Z",
        "band": "10",
        "frequency": "28180.0",
        "spotted": "DN9STW",
        "spotted_dxcc": "230",
        "spotted_flag": "DE",
        "spotted_country": "FEDERAL REPUBLIC OF GERMANY",
        "spotted_continent": "EU",
        "spotter": "KD2WDR",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "rtty",
        "spotter_comment": "FT4 0dB 1672 Hz CQ            "
    },
    {
        "spot_datetime": "2026-02-18 16:08:56",
        "spot_time": "1608Z",
        "band": "15",
        "frequency": "21075.3",
        "spotted": "W4FO",
        "spotted_dxcc": "291",
        "spotted_flag": "US",
        "spotted_country": "UNITED STATES OF AMERICA",
        "spotted_continent": "NA",
        "spotter": "EA4FME",
        "spotter_dxcc": "281",
        "spotter_flag": "ES",
        "spotter_country": "SPAIN",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": "IN80GN<>EL88PI FT8 FT8  Sent: "
    },
    {
        "spot_datetime": "2026-02-18 16:08:44",
        "spot_time": "1608Z",
        "band": "40",
        "frequency": "7172.0",
        "spotted": "EA2CCG\/P",
        "spotted_dxcc": "281",
        "spotted_flag": "ES",
        "spotted_country": "SPAIN",
        "spotted_continent": "EU",
        "spotter": "EA4IFN",
        "spotter_dxcc": "281",
        "spotter_flag": "ES",
        "spotter_country": "SPAIN",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": "POTA ES-2280 ES-1782          "
    },
    {
        "spot_datetime": "2026-02-18 16:08:40",
        "spot_time": "1607Z",
        "band": "10",
        "frequency": "28180.0",
        "spotted": "PV8BR",
        "spotted_dxcc": "108",
        "spotted_flag": "BR",
        "spotted_country": "BRAZIL",
        "spotted_continent": "SA",
        "spotter": "PU2LJH",
        "spotter_dxcc": "108",
        "spotter_flag": "BR",
        "spotter_country": "BRAZIL",
        "spotter_continent": "SA",
        "mode": "lsb",
        "spotter_comment": "tnx qso Francisco 73          "
    },
    {
        "spot_datetime": "2026-02-18 16:08:36",
        "spot_time": "1608Z",
        "band": "15",
        "frequency": "21075.4",
        "spotted": "EW4M",
        "spotted_dxcc": "27",
        "spotted_flag": "BY",
        "spotted_country": "BELARUS",
        "spotted_continent": "EU",
        "spotter": "KX2S",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "cw",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:08:32",
        "spot_time": "1608Z",
        "band": "10",
        "frequency": "28052.0",
        "spotted": "ZV8AP",
        "spotted_dxcc": "108",
        "spotted_flag": "BR",
        "spotted_country": "BRAZIL",
        "spotted_continent": "SA",
        "spotter": "PY3OZ",
        "spotter_dxcc": "108",
        "spotter_flag": "BR",
        "spotter_country": "BRAZIL",
        "spotter_continent": "SA",
        "mode": "ft8",
        "spotter_comment": "LABRE AWARDS 92 YEARS         "
    },
    {
        "spot_datetime": "2026-02-18 16:08:27",
        "spot_time": "1608Z",
        "band": "20",
        "frequency": "14247.0",
        "spotted": "W1AW\/8",
        "spotted_dxcc": "291",
        "spotted_flag": "US",
        "spotted_country": "UNITED STATES OF AMERICA",
        "spotted_continent": "NA",
        "spotter": "N8QYQ",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "ft8",
        "spotter_comment": "USB ARRL AMERICA 250 WAS EVENT"
    },
    {
        "spot_datetime": "2026-02-18 16:08:19",
        "spot_time": "1608Z",
        "band": "10",
        "frequency": "28052.0",
        "spotted": "ZV8PI",
        "spotted_dxcc": "108",
        "spotted_flag": "BR",
        "spotted_country": "BRAZIL",
        "spotted_continent": "SA",
        "spotter": "PY3OZ",
        "spotter_dxcc": "108",
        "spotter_flag": "BR",
        "spotter_country": "BRAZIL",
        "spotter_continent": "SA",
        "mode": "usb",
        "spotter_comment": "LABRE AWARDS 92 YEARS         "
    },
    {
        "spot_datetime": "2026-02-18 16:07:53",
        "spot_time": "1607Z",
        "band": "10",
        "frequency": "28434.8",
        "spotted": "J52EC",
        "spotted_dxcc": "109",
        "spotted_flag": "GW",
        "spotted_country": "GUINEA-BISSAU",
        "spotted_continent": "AF",
        "spotter": "EA1K",
        "spotter_dxcc": "281",
        "spotter_flag": "ES",
        "spotter_country": "SPAIN",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": "CQ                            "
    },
    {
        "spot_datetime": "2026-02-18 16:07:49",
        "spot_time": "1607Z",
        "band": "10",
        "frequency": "28181.4",
        "spotted": "VA3KL",
        "spotted_dxcc": "1",
        "spotted_flag": "CA",
        "spotted_country": "CANADA",
        "spotted_continent": "NA",
        "spotter": "IZ7HNO",
        "spotter_dxcc": "248",
        "spotter_flag": "IT",
        "spotter_country": "ITALY",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": "DXCC 1 VUCC FN04 WAC NA WAZ 4 "
    },
    {
        "spot_datetime": "2026-02-18 16:07:45",
        "spot_time": "1607Z",
        "band": "10",
        "frequency": "28181.5",
        "spotted": "VA3NSC",
        "spotted_dxcc": "1",
        "spotted_flag": "CA",
        "spotted_country": "CANADA",
        "spotted_continent": "NA",
        "spotter": "IZ7HNO",
        "spotter_dxcc": "248",
        "spotter_flag": "IT",
        "spotter_country": "ITALY",
        "spotter_continent": "EU",
        "mode": "usb",
        "spotter_comment": "DXCC 1 VUCC FN15 WAC NA WAZ 4 "
    },
    {
        "spot_datetime": "2026-02-18 16:07:41",
        "spot_time": "1607Z",
        "band": "17",
        "frequency": "18082.0",
        "spotted": "N3RN",
        "spotted_dxcc": "291",
        "spotted_flag": "US",
        "spotted_country": "UNITED STATES OF AMERICA",
        "spotted_continent": "NA",
        "spotter": "NU4N",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "ft8",
        "spotter_comment": "US POTA 4615 FLORIDA          "
    },
    {
        "spot_datetime": "2026-02-18 16:07:36",
        "spot_time": "1607Z",
        "band": "10",
        "frequency": "28503.0",
        "spotted": "HG80EARTH",
        "spotted_dxcc": "239",
        "spotted_flag": "HU",
        "spotted_country": "HUNGARY",
        "spotted_continent": "EU",
        "spotter": "N9ITB",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "lsb",
        "spotter_comment": "57 LaPorte, Indiana           "
    },
    {
        "spot_datetime": "2026-02-18 16:07:32",
        "spot_time": "1607Z",
        "band": "15",
        "frequency": "21075.4",
        "spotted": "HB3YDV",
        "spotted_dxcc": "287",
        "spotted_flag": "CH",
        "spotted_country": "SWITZERLAND",
        "spotted_continent": "EU",
        "spotter": "KX2S",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "lsb",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:07:08",
        "spot_time": "1607Z",
        "band": "10",
        "frequency": "28405.0",
        "spotted": "LU9HAT",
        "spotted_dxcc": "100",
        "spotted_flag": "AR",
        "spotted_country": "ARGENTINA",
        "spotted_continent": "SA",
        "spotter": "IZ1WYO",
        "spotter_dxcc": "248",
        "spotter_flag": "IT",
        "spotter_country": "ITALY",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:06:36",
        "spot_time": "1606Z",
        "band": "10",
        "frequency": "28495.0",
        "spotted": "7X3WPL",
        "spotted_dxcc": "400",
        "spotted_flag": "DZ",
        "spotted_country": "ALGERIA",
        "spotted_continent": "AF",
        "spotter": "M9MOF",
        "spotter_dxcc": "223",
        "spotter_flag": "GB-ENG",
        "spotter_country": "ENGLAND",
        "spotter_continent": "EU",
        "mode": "rtty",
        "spotter_comment": "59 Lake District England      "
    },
    {
        "spot_datetime": "2026-02-18 16:06:29",
        "spot_time": "1606Z",
        "band": "15",
        "frequency": "21245.0",
        "spotted": "EA4DE",
        "spotted_dxcc": "281",
        "spotted_flag": "ES",
        "spotted_country": "SPAIN",
        "spotted_continent": "EU",
        "spotter": "OH0M",
        "spotter_dxcc": "5",
        "spotter_flag": "AX",
        "spotter_country": "ALAND ISLANDS",
        "spotter_continent": "EU",
        "mode": "rtty",
        "spotter_comment": "WWFF EAFF-2688                "
    },
    {
        "spot_datetime": "2026-02-18 16:06:17",
        "spot_time": "1606Z",
        "band": "10",
        "frequency": "28455.0",
        "spotted": "9A8DX",
        "spotted_dxcc": "497",
        "spotted_flag": "HR",
        "spotted_country": "CROATIA",
        "spotted_continent": "EU",
        "spotter": "W3EGW",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "ft8",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:06:13",
        "spot_time": "1606Z",
        "band": "023",
        "frequency": "1296850.0",
        "spotted": "GB3FRS\/B",
        "spotted_dxcc": "223",
        "spotted_flag": "GB-ENG",
        "spotted_country": "ENGLAND",
        "spotted_continent": "EU",
        "spotter": "G0API",
        "spotter_dxcc": "223",
        "spotter_flag": "GB-ENG",
        "spotter_country": "ENGLAND",
        "spotter_continent": "EU",
        "mode": "lsb",
        "spotter_comment": "IO80XS IO91LC 569          "
    },
    {
        "spot_datetime": "2026-02-18 16:06:09",
        "spot_time": "1605Z",
        "band": "10",
        "frequency": "28180.0",
        "spotted": "ZV8PA",
        "spotted_dxcc": "108",
        "spotted_flag": "BR",
        "spotted_country": "BRAZIL",
        "spotted_continent": "SA",
        "spotter": "PY5CC",
        "spotter_dxcc": "108",
        "spotter_flag": "BR",
        "spotter_country": "BRAZIL",
        "spotter_continent": "SA",
        "mode": "ft8",
        "spotter_comment": "FT4 Labre 92 Years            "
    },
    {
        "spot_datetime": "2026-02-18 16:06:04",
        "spot_time": "1606Z",
        "band": "10",
        "frequency": "28542.0",
        "spotted": "2W0LVE",
        "spotted_dxcc": "294",
        "spotted_flag": "GB-WLS",
        "spotted_country": "WALES",
        "spotted_continent": "EU",
        "spotter": "AB2KL",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "lsb",
        "spotter_comment": "cq                            "
    },
    {
        "spot_datetime": "2026-02-18 16:05:39",
        "spot_time": "1605Z",
        "band": "20",
        "frequency": "14130.0",
        "spotted": "F5PYI",
        "spotted_dxcc": "227",
        "spotted_flag": "FR",
        "spotted_country": "FRANCE",
        "spotted_continent": "EU",
        "spotter": "PD3RL",
        "spotter_dxcc": "263",
        "spotter_flag": "NL",
        "spotter_country": "NETHERLANDS",
        "spotter_continent": "EU",
        "mode": "usb",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:05:34",
        "spot_time": "1605Z",
        "band": "023",
        "frequency": "1296830.0",
        "spotted": "GB3MHZ\/B",
        "spotted_dxcc": "223",
        "spotted_flag": "GB-ENG",
        "spotted_country": "ENGLAND",
        "spotted_continent": "EU",
        "spotter": "G0API",
        "spotter_dxcc": "223",
        "spotter_flag": "GB-ENG",
        "spotter_country": "ENGLAND",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": "IO80XS JO02PB 529          "
    },
    {
        "spot_datetime": "2026-02-18 16:05:30",
        "spot_time": "1605Z",
        "band": "40",
        "frequency": "7177.0",
        "spotted": "IU0KNS",
        "spotted_dxcc": "248",
        "spotted_flag": "IT",
        "spotted_country": "ITALY",
        "spotted_continent": "EU",
        "spotter": "IW0EMQ",
        "spotter_dxcc": "248",
        "spotter_flag": "IT",
        "spotter_country": "ITALY",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": "BUONGIORNO ITALIA             "
    },
    {
        "spot_datetime": "2026-02-18 16:05:25",
        "spot_time": "1604Z",
        "band": "10",
        "frequency": "28180.0",
        "spotted": "ZV5PR",
        "spotted_dxcc": "108",
        "spotted_flag": "BR",
        "spotted_country": "BRAZIL",
        "spotted_continent": "SA",
        "spotter": "PY5CC",
        "spotter_dxcc": "108",
        "spotter_flag": "BR",
        "spotter_country": "BRAZIL",
        "spotter_continent": "SA",
        "mode": "rtty",
        "spotter_comment": "FT4 Labre 92 Years            "
    },
    {
        "spot_datetime": "2026-02-18 16:05:21",
        "spot_time": "1605Z",
        "band": "10",
        "frequency": "28180.0",
        "spotted": "DN9STW",
        "spotted_dxcc": "230",
        "spotted_flag": "DE",
        "spotted_country": "FEDERAL REPUBLIC OF GERMANY",
        "spotted_continent": "EU",
        "spotter": "KD2WDR",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "lsb",
        "spotter_comment": "FT4 -3dB 1671 Hz CQ           "
    },
    {
        "spot_datetime": "2026-02-18 16:05:17",
        "spot_time": "1605Z",
        "band": "15",
        "frequency": "21203.0",
        "spotted": "VE9CF",
        "spotted_dxcc": "1",
        "spotted_flag": "CA",
        "spotted_country": "CANADA",
        "spotted_continent": "NA",
        "spotter": "HA5CPN",
        "spotter_dxcc": "239",
        "spotter_flag": "HU",
        "spotter_country": "HUNGARY",
        "spotter_continent": "EU",
        "mode": "cw",
        "spotter_comment": "All the best_5.9_TNX_QSO      "
    },
    {
        "spot_datetime": "2026-02-18 16:04:56",
        "spot_time": "1604Z",
        "band": "40",
        "frequency": "7088.0",
        "spotted": "EA2DT\/P",
        "spotted_dxcc": "281",
        "spotted_flag": "ES",
        "spotted_country": "SPAIN",
        "spotted_continent": "EU",
        "spotter": "EA2DT",
        "spotter_dxcc": "281",
        "spotter_flag": "ES",
        "spotter_country": "SPAIN",
        "spotter_continent": "EU",
        "mode": "usb",
        "spotter_comment": "POTA ES-1843                  "
    },
    {
        "spot_datetime": "2026-02-18 16:04:52",
        "spot_time": "1604Z",
        "band": "17",
        "frequency": "18149.0",
        "spotted": "IZ2DPX",
        "spotted_dxcc": "248",
        "spotted_flag": "IT",
        "spotted_country": "ITALY",
        "spotted_continent": "EU",
        "spotter": "II2V",
        "spotter_dxcc": "248",
        "spotter_flag": "IT",
        "spotter_country": "ITALY",
        "spotter_continent": "EU",
        "mode": "lsb",
        "spotter_comment": "SSB Volta Award 2026          "
    },
    {
        "spot_datetime": "2026-02-18 16:04:47",
        "spot_time": "1604Z",
        "band": "15",
        "frequency": "21075.4",
        "spotted": "LZ3AN",
        "spotted_dxcc": "212",
        "spotted_flag": "BG",
        "spotted_country": "BULGARIA",
        "spotted_continent": "EU",
        "spotter": "KX2S",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "lsb",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:04:43",
        "spot_time": "1604Z",
        "band": "20",
        "frequency": "14081.3",
        "spotted": "ME1JDU",
        "spotted_dxcc": "223",
        "spotted_flag": "GB-ENG",
        "spotted_country": "ENGLAND",
        "spotted_continent": "EU",
        "spotter": "F4BJN",
        "spotter_dxcc": "227",
        "spotter_flag": "FR",
        "spotter_country": "FRANCE",
        "spotter_continent": "EU",
        "mode": "cw",
        "spotter_comment": "FT4 -05 Thx for qso 73        "
    },
    {
        "spot_datetime": "2026-02-18 16:04:35",
        "spot_time": "1604Z",
        "band": "40",
        "frequency": "7127.0",
        "spotted": "IZ0PAP",
        "spotted_dxcc": "248",
        "spotted_flag": "IT",
        "spotted_country": "ITALY",
        "spotted_continent": "EU",
        "spotter": "IK0FFU",
        "spotter_dxcc": "248",
        "spotter_flag": "IT",
        "spotter_country": "ITALY",
        "spotter_continent": "EU",
        "mode": "rtty",
        "spotter_comment": "cortina olim.                 "
    },
    {
        "spot_datetime": "2026-02-18 16:04:29",
        "spot_time": "1604Z",
        "band": "40",
        "frequency": "7037.0",
        "spotted": "OK3SN\/P",
        "spotted_dxcc": "503",
        "spotted_flag": "CZ",
        "spotted_country": "CZECH REPUBLIC",
        "spotted_continent": "EU",
        "spotter": "OH0M",
        "spotter_dxcc": "5",
        "spotter_flag": "AX",
        "spotter_country": "ALAND ISLANDS",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": "WWFF OKFF-0023                "
    },
    {
        "spot_datetime": "2026-02-18 16:04:24",
        "spot_time": "1604Z",
        "band": "023",
        "frequency": "1296800.0",
        "spotted": "GB3IOW\/B",
        "spotted_dxcc": "223",
        "spotted_flag": "GB-ENG",
        "spotted_country": "ENGLAND",
        "spotted_continent": "EU",
        "spotter": "G0API",
        "spotter_dxcc": "223",
        "spotter_flag": "GB-ENG",
        "spotter_country": "ENGLAND",
        "spotter_continent": "EU",
        "mode": "usb",
        "spotter_comment": "IO80XS IO90IR 599          "
    },
    {
        "spot_datetime": "2026-02-18 16:04:20",
        "spot_time": "1604Z",
        "band": "17",
        "frequency": "18102.0",
        "spotted": "IZ4MJP",
        "spotted_dxcc": "248",
        "spotted_flag": "IT",
        "spotted_country": "ITALY",
        "spotted_continent": "EU",
        "spotter": "KB8OTK",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "rtty",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:04:15",
        "spot_time": "1604Z",
        "band": "40",
        "frequency": "7079.0",
        "spotted": "EA4AKF",
        "spotted_dxcc": "281",
        "spotted_flag": "ES",
        "spotted_country": "SPAIN",
        "spotted_continent": "EU",
        "spotter": "EA9QD",
        "spotter_dxcc": "32",
        "spotter_flag": "ES",
        "spotter_country": "CEUTA & MELILLA",
        "spotter_continent": "AF",
        "mode": "lsb",
        "spotter_comment": "trofeo hermandads del rocio   "
    },
    {
        "spot_datetime": "2026-02-18 16:04:11",
        "spot_time": "1604Z",
        "band": "40",
        "frequency": "7155.0",
        "spotted": "E75YZ",
        "spotted_dxcc": "501",
        "spotted_flag": "BA",
        "spotted_country": "BOSNIA-HERZEGOVINA",
        "spotted_continent": "EU",
        "spotter": "PD3RL",
        "spotter_dxcc": "263",
        "spotter_flag": "NL",
        "spotter_country": "NETHERLANDS",
        "spotter_continent": "EU",
        "mode": "rtty",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:04:07",
        "spot_time": "1604Z",
        "band": "2",
        "frequency": "144174.0",
        "spotted": "DO1FOX",
        "spotted_dxcc": "230",
        "spotted_flag": "DE",
        "spotted_country": "FEDERAL REPUBLIC OF GERMANY",
        "spotted_continent": "EU",
        "spotter": "G4TRA",
        "spotter_dxcc": "223",
        "spotter_flag": "GB-ENG",
        "spotter_country": "ENGLAND",
        "spotter_continent": "EU",
        "mode": "usb",
        "spotter_comment": "KLAPPT NICHT GUT              "
    },
    {
        "spot_datetime": "2026-02-18 16:04:03",
        "spot_time": "1604Z",
        "band": "17",
        "frequency": "18091.0",
        "spotted": "P44W",
        "spotted_dxcc": "91",
        "spotted_flag": "AW",
        "spotted_country": "ARUBA",
        "spotted_continent": "SA",
        "spotter": "AD0K",
        "spotter_dxcc": "291",
        "spotter_flag": "US",
        "spotter_country": "UNITED STATES OF AMERICA",
        "spotter_continent": "NA",
        "mode": "usb",
        "spotter_comment": "CW IOTA SA-036                "
    },
    {
        "spot_datetime": "2026-02-18 16:03:51",
        "spot_time": "1603Z",
        "band": "10",
        "frequency": "28074.0",
        "spotted": "F6JON",
        "spotted_dxcc": "227",
        "spotted_flag": "FR",
        "spotted_country": "FRANCE",
        "spotted_continent": "EU",
        "spotter": "YB1PEF",
        "spotter_dxcc": "327",
        "spotter_flag": "ID",
        "spotter_country": "INDONESIA",
        "spotter_continent": "OC",
        "mode": "rtty",
        "spotter_comment": "FT8 -06dB 1844Hz              "
    },
    {
        "spot_datetime": "2026-02-18 16:03:47",
        "spot_time": "1603Z",
        "band": "30",
        "frequency": "10130.0",
        "spotted": "EA3FNZ",
        "spotted_dxcc": "281",
        "spotted_flag": "ES",
        "spotted_country": "SPAIN",
        "spotted_continent": "EU",
        "spotter": "EA3WX",
        "spotter_dxcc": "281",
        "spotter_flag": "ES",
        "spotter_country": "SPAIN",
        "spotter_continent": "EU",
        "mode": "cw",
        "spotter_comment": "DME 25048                     "
    },
    {
        "spot_datetime": "2026-02-18 16:03:41",
        "spot_time": "1603Z",
        "band": "12",
        "frequency": "24915.0",
        "spotted": "DA0ANT",
        "spotted_dxcc": "230",
        "spotted_flag": "DE",
        "spotted_country": "FEDERAL REPUBLIC OF GERMANY",
        "spotted_continent": "EU",
        "spotter": "DL1GLO",
        "spotter_dxcc": "230",
        "spotter_flag": "DE",
        "spotter_country": "FEDERAL REPUBLIC OF GERMANY",
        "spotter_continent": "EU",
        "mode": "lsb",
        "spotter_comment": "FT8 -04dB 1791Hz              "
    },
    {
        "spot_datetime": "2026-02-18 16:03:36",
        "spot_time": "1603Z",
        "band": "12",
        "frequency": "24896.0",
        "spotted": "HG80EME",
        "spotted_dxcc": "239",
        "spotted_flag": "HU",
        "spotted_country": "HUNGARY",
        "spotted_continent": "EU",
        "spotter": "HA7TM",
        "spotter_dxcc": "239",
        "spotter_flag": "HU",
        "spotter_country": "HUNGARY",
        "spotter_continent": "EU",
        "mode": "rtty",
        "spotter_comment": "CW CQ                         "
    },
    {
        "spot_datetime": "2026-02-18 16:03:32",
        "spot_time": "1603Z",
        "band": "20",
        "frequency": "14306.0",
        "spotted": "MM0VIK",
        "spotted_dxcc": "279",
        "spotted_flag": "GB-SCT",
        "spotted_country": "SCOTLAND",
        "spotted_continent": "EU",
        "spotter": "IZ1HHT",
        "spotter_dxcc": "248",
        "spotter_flag": "IT",
        "spotter_country": "ITALY",
        "spotter_continent": "EU",
        "mode": "cw",
        "spotter_comment": "Parks On The Air new QRG      "
    },
    {
        "spot_datetime": "2026-02-18 16:03:27",
        "spot_time": "1603Z",
        "band": "10",
        "frequency": "28405.0",
        "spotted": "LU9HAT",
        "spotted_dxcc": "100",
        "spotted_flag": "AR",
        "spotted_country": "ARGENTINA",
        "spotted_continent": "SA",
        "spotter": "IU5PTB",
        "spotter_dxcc": "248",
        "spotter_flag": "IT",
        "spotter_country": "ITALY",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": "tnx fer qso 73                "
    },
    {
        "spot_datetime": "2026-02-18 16:03:19",
        "spot_time": "1603Z",
        "band": "12",
        "frequency": "24942.0",
        "spotted": "OM2ADM",
        "spotted_dxcc": "504",
        "spotted_flag": "SK",
        "spotted_country": "SLOVAK REPUBLIC",
        "spotted_continent": "EU",
        "spotter": "OM2ADM",
        "spotter_dxcc": "504",
        "spotter_flag": "SK",
        "spotter_country": "SLOVAK REPUBLIC",
        "spotter_continent": "EU",
        "mode": "rtty",
        "spotter_comment": "DXPedition mode               "
    },
    {
        "spot_datetime": "2026-02-18 16:03:14",
        "spot_time": "1603Z",
        "band": "40",
        "frequency": "7196.0",
        "spotted": "9A\/TA1BYS",
        "spotted_dxcc": "497",
        "spotted_flag": "HR",
        "spotted_country": "CROATIA",
        "spotted_continent": "EU",
        "spotter": "F4LBD",
        "spotter_dxcc": "227",
        "spotter_flag": "FR",
        "spotter_country": "FRANCE",
        "spotter_continent": "EU",
        "mode": "rtty",
        "spotter_comment": "73 Mustafa                    "
    },
    {
        "spot_datetime": "2026-02-18 16:03:01",
        "spot_time": "1602Z",
        "band": "40",
        "frequency": "7021.5",
        "spotted": "HG80EARTH",
        "spotted_dxcc": "239",
        "spotted_flag": "HU",
        "spotted_country": "HUNGARY",
        "spotted_continent": "EU",
        "spotter": "DK5HH",
        "spotter_dxcc": "230",
        "spotter_flag": "DE",
        "spotter_country": "FEDERAL REPUBLIC OF GERMANY",
        "spotter_continent": "EU",
        "mode": "ft8",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:02:55",
        "spot_time": "1602Z",
        "band": "000",
        "frequency": "24048905.1",
        "spotted": "GB3SCK\/B",
        "spotted_dxcc": "223",
        "spotted_flag": "GB-ENG",
        "spotted_country": "ENGLAND",
        "spotted_continent": "EU",
        "spotter": "G0API",
        "spotter_dxcc": "223",
        "spotter_flag": "GB-ENG",
        "spotter_country": "ENGLAND",
        "spotter_continent": "EU",
        "mode": "usb",
        "spotter_comment": "IO80XS IO80UU 599          "
    },
    {
        "spot_datetime": "2026-02-18 16:02:51",
        "spot_time": "1602Z",
        "band": "OOB",
        "frequency": "1434800.0",
        "spotted": "J52EC",
        "spotted_dxcc": "109",
        "spotted_flag": "GW",
        "spotted_country": "GUINEA-BISSAU",
        "spotted_continent": "AF",
        "spotter": "HP6DJA",
        "spotter_dxcc": "88",
        "spotter_flag": "PA",
        "spotter_country": "PANAMA",
        "spotter_continent": "NA",
        "mode": "rtty",
        "spotter_comment": "CQ DX                         "
    },
    {
        "spot_datetime": "2026-02-18 16:02:47",
        "spot_time": "1602Z",
        "band": "10",
        "frequency": "28011.0",
        "spotted": "ZV2SP",
        "spotted_dxcc": "108",
        "spotted_flag": "BR",
        "spotted_country": "BRAZIL",
        "spotted_continent": "SA",
        "spotter": "LW5DD",
        "spotter_dxcc": "100",
        "spotter_flag": "AR",
        "spotter_country": "ARGENTINA",
        "spotter_continent": "SA",
        "mode": "ft8",
        "spotter_comment": ""
    },
    {
        "spot_datetime": "2026-02-18 16:02:32",
        "spot_time": "1602Z",
        "band": "10",
        "frequency": "28012.0",
        "spotted": "W1AW",
        "spotted_dxcc": "291",
        "spotted_flag": "US",
        "spotted_country": "UNITED STATES OF AMERICA",
        "spotted_continent": "NA",
        "spotter": "IU8GBG",
        "spotter_dxcc": "248",
        "spotter_flag": "IT",
        "spotter_country": "ITALY",
        "spotter_continent": "EU",
        "mode": "lsb",
        "spotter_comment": "tnx!!!!!                      "
    }
];